language: clojure
script:
  - lein compile
  - lein jar
  - lein cljsbuild once env-ini
  - lein cljsbuild once node
  - lein test
jdk:
  - oraclejdk8
  - oraclejdk7
  - openjdk6
  - openjdk7
notifications:
  email:
      - oubiwann@gmail.com
